// ─── Global AI Insight Data — FOUNDATION-GLOBAL-AI-INSIGHT-001 ───────────────
//
// Single Source of Truth untuk seluruh insight, analisis, rekomendasi,
// dan peringatan yang dihasilkan sistem TernakHub.
//
// ATURAN:
//   • Semua modul menghasilkan insight HANYA melalui globalAiInsightService.ts.
//   • Akses langsung ke GLOBAL_AI_INSIGHT_DB atau fungsi _* dilarang dari luar.
//   • Engine ini TIDAK melakukan AI inference — ia menjadi pusat penyimpanan,
//     manajemen, dan distribusi insight yang dihasilkan oleh modul lain.
//   • Insight HARUS explainable, evidence-based, dan data-driven.
//   • AI TIDAK boleh membuat kesimpulan tanpa evidence.
//   • insight_type, insight_status, priority, entity_type HARUS menggunakan UUID
//     dari Global Reference Service.
//   • UUID bersifat stabil — jangan diregenerasi setelah ditetapkan.
//
// RELASI YANG DISIAPKAN (belum di-wire):
//   evidence_score  → Global Evidence Service
//   trust update    → Global Trust Service (verification_score feed-in)
//   audit log       → Global Audit Trail Service
//   activity log    → Global Activity Service
//   search index    → Global Search Service
//   entity_uuid     → Livestock / Feed / Medicine / Marketplace / Transaction
// ─────────────────────────────────────────────────────────────────────────────

import { generateUUID } from '../utils/uuid';

// ─── UUID Konstanta — Insight Type ───────────────────────────────────────────
// Stabil — sesuai seed di globalReferenceData.ts.

export const INSIGHT_TYPE_UUID = {
  NUTRITION:      'ba000001-0000-4000-a000-000000000001',
  WEIGHT:         'ba000001-0000-4000-a000-000000000002',
  GROWTH:         'ba000001-0000-4000-a000-000000000003',
  HEALTH:         'ba000001-0000-4000-a000-000000000004',
  MEDICINE:       'ba000001-0000-4000-a000-000000000005',
  MARKETPLACE:    'ba000001-0000-4000-a000-000000000006',
  PRICE:          'ba000001-0000-4000-a000-000000000007',
  FEED_COST:      'ba000001-0000-4000-a000-000000000008',
  INVENTORY:      'ba000001-0000-4000-a000-000000000009',
  PRODUCTIVITY:   'ba000001-0000-4000-a000-000000000010',
  TRUST:          'ba000001-0000-4000-a000-000000000011',
  VERIFICATION:   'ba000001-0000-4000-a000-000000000012',
  FINANCIAL:      'ba000001-0000-4000-a000-000000000013',
  REMINDER:       'ba000001-0000-4000-a000-000000000014',
  WARNING:        'ba000001-0000-4000-a000-000000000015',
  RECOMMENDATION: 'ba000001-0000-4000-a000-000000000016',
} as const;

export type InsightTypeUuid = (typeof INSIGHT_TYPE_UUID)[keyof typeof INSIGHT_TYPE_UUID];

// ─── UUID Konstanta — Insight Status ─────────────────────────────────────────

export const INSIGHT_STATUS_UUID = {
  ACTIVE:    'bb000001-0000-4000-a000-000000000001',
  ARCHIVED:  'bb000001-0000-4000-a000-000000000002',
  EXPIRED:   'bb000001-0000-4000-a000-000000000003',
  DISMISSED: 'bb000001-0000-4000-a000-000000000004',
} as const;

export type InsightStatusUuid =
  (typeof INSIGHT_STATUS_UUID)[keyof typeof INSIGHT_STATUS_UUID];

// ─── UUID Konstanta — Priority (dari FOUNDATION-007) ─────────────────────────

export const INSIGHT_PRIORITY_UUID = {
  LOW:      'a9000001-0000-4000-a000-000000000001',
  NORMAL:   'a9000001-0000-4000-a000-000000000002',
  HIGH:     'a9000001-0000-4000-a000-000000000003',
  CRITICAL: 'a9000001-0000-4000-a000-000000000004',
} as const;

export type InsightPriorityUuid =
  (typeof INSIGHT_PRIORITY_UUID)[keyof typeof INSIGHT_PRIORITY_UUID];

// ─── Source Module ────────────────────────────────────────────────────────────
// Modul yang menghasilkan insight. Digunakan pada field source_module.

export type InsightSourceModule =
  | 'livestock'
  | 'batch'
  | 'feed'
  | 'feed_formula'
  | 'feed_stock'
  | 'medicine'
  | 'medicine_stock'
  | 'health'
  | 'reproduksi'
  | 'mutation'
  | 'marketplace'
  | 'transaction'
  | 'escrow'
  | 'evidence'
  | 'trust'
  | 'verification'
  | 'news_event'
  | 'profile'
  | 'workspace'
  | 'system';

// ─── Generated By ─────────────────────────────────────────────────────────────
// Mekanisme yang menghasilkan insight.

export type InsightGeneratedBy =
  | 'rule_based'     // Aturan bisnis deterministik (paling umum sekarang)
  | 'statistical'    // Perhitungan statistik sederhana (rata-rata, standar deviasi)
  | 'system';        // Dihasilkan otomatis oleh sistem platform

// ─── Schema — AiInsightRecord ─────────────────────────────────────────────────

export interface AiInsightRecord {
  /** UUID v4 — primary key. Immutable setelah ditetapkan. */
  insight_uuid: string;

  /**
   * Jenis insight — UUID ke INSIGHT_TYPE di Global Reference.
   * Gunakan INSIGHT_TYPE_UUID untuk referensi stabil.
   */
  insight_type_reference_uuid: string;

  /**
   * Status siklus hidup — UUID ke INSIGHT_STATUS.
   * Gunakan INSIGHT_STATUS_UUID untuk referensi stabil.
   */
  insight_status_reference_uuid: string;

  /**
   * Tingkat prioritas — UUID ke PRIORITY di Global Reference (FOUNDATION-007).
   * Gunakan INSIGHT_PRIORITY_UUID untuk referensi stabil.
   * Default: Normal.
   */
  priority_reference_uuid: string;

  /**
   * Workspace yang menerima insight ini.
   * null = insight global/sistem yang tidak terikat workspace.
   */
  workspace_uuid: string | null;

  /**
   * Jenis entity yang menjadi subjek insight — UUID ke ENTITY_TYPE.
   * null = insight lintas entity atau sistem.
   */
  entity_type_reference_uuid: string | null;

  /**
   * UUID entity yang menjadi subjek insight.
   * Contoh: livestock.id, batch_uuid, listing_uuid.
   * null = insight tidak merujuk entitas spesifik.
   */
  entity_uuid: string | null;

  /**
   * Judul singkat insight untuk tampilan.
   * Contoh: 'ADG di Bawah Target', 'Stok Pakan Kritis'.
   * Maks 200 karakter. Wajib diisi.
   */
  title: string;

  /**
   * Ringkasan satu-dua kalimat untuk tampilan kompak.
   * Contoh: 'ADG 180g/hari — 28% di bawah target 250g/hari selama 14 hari.'.
   * Wajib diisi.
   */
  summary: string;

  /**
   * Penjelasan lengkap insight — data, tren, dan konteks yang mendasari.
   * null = summary sudah cukup.
   */
  description: string | null;

  /**
   * Rekomendasi tindakan yang dapat dilakukan pengguna.
   * null = insight bersifat informatif tanpa rekomendasi spesifik.
   */
  recommendation: string | null;

  /**
   * Tingkat keyakinan sistem terhadap insight (0.00–1.00).
   * 1.00 = pasti (rule-based dengan data lengkap).
   * < 0.5 = tidak cukup data untuk kesimpulan yang kuat.
   * null = belum dihitung.
   */
  confidence_score: number | null;

  /**
   * Skor kualitas evidence yang mendukung insight (0–100).
   * Berasal dari Global Evidence Service — belum di-wire.
   * null = tidak ada evidence spesifik.
   */
  evidence_score: number | null;

  /** Mekanisme yang menghasilkan insight. */
  generated_by: InsightGeneratedBy;

  /** Modul yang menghasilkan insight. */
  source_module: InsightSourceModule;

  /**
   * Timestamp ISO 8601 kapan insight ini dihasilkan (bisa berbeda dari created_at
   * jika insight di-backfill atau di-import).
   */
  generated_at: string;

  /**
   * Timestamp ISO 8601 kapan insight ini kedaluwarsa.
   * null = tidak ada masa berlaku (insight permanen sampai diarsipkan secara eksplisit).
   */
  expired_at: string | null;

  /** Timestamp ISO 8601 saat record pertama dibuat. */
  created_at: string;

  /** Timestamp ISO 8601 saat record terakhir diperbarui. */
  updated_at: string;
}

// ─── Input untuk createInsight ────────────────────────────────────────────────

export interface CreateInsightInput {
  insight_type_reference_uuid: string;
  priority_reference_uuid?: string;
  workspace_uuid?: string | null;
  entity_type_reference_uuid?: string | null;
  entity_uuid?: string | null;
  title: string;
  summary: string;
  description?: string | null;
  recommendation?: string | null;
  confidence_score?: number | null;
  evidence_score?: number | null;
  generated_by?: InsightGeneratedBy;
  source_module: InsightSourceModule;
  /** Timestamp kapan insight dihasilkan. Default: sekarang. */
  generated_at?: string;
  /** Masa berlaku. null = tidak kedaluwarsa. */
  expired_at?: string | null;
}

// ─── Filter untuk getInsight ──────────────────────────────────────────────────

export interface GetInsightFilter {
  workspace_uuid?: string;
  insight_type_reference_uuid?: string;
  insight_status_reference_uuid?: string;
  priority_reference_uuid?: string;
  entity_type_reference_uuid?: string;
  entity_uuid?: string;
  source_module?: InsightSourceModule;
  generated_by?: InsightGeneratedBy;
  /** Jika true, hanya Active insight. Default: true. */
  active_only?: boolean;
  /** Jika true, sertakan Expired insight. Default: false. */
  include_expired?: boolean;
  /** Minimum confidence_score (0.00–1.00). */
  min_confidence?: number;
  /** Hanya insight pada atau setelah timestamp ini (generated_at). */
  from_date?: string;
  /** Hanya insight pada atau sebelum timestamp ini (generated_at). */
  to_date?: string;
  limit?: number;
  offset?: number;
}

// ─── In-Memory Store ──────────────────────────────────────────────────────────
// INTERNAL — akses hanya melalui globalAiInsightService.ts.

export const GLOBAL_AI_INSIGHT_DB: Map<string, AiInsightRecord> = new Map();

// ─── Internal Helpers (package-private) ───────────────────────────────────────

export function _insertInsight(record: AiInsightRecord): void {
  GLOBAL_AI_INSIGHT_DB.set(record.insight_uuid, record);
}

export function _replaceInsight(record: AiInsightRecord): void {
  GLOBAL_AI_INSIGHT_DB.set(record.insight_uuid, record);
}

export function _getAllInsights(): AiInsightRecord[] {
  return Array.from(GLOBAL_AI_INSIGHT_DB.values());
}

// Re-export generateUUID agar service layer tidak import dari utils langsung.
export { generateUUID };
